### ISSUE TITLE
NumWorks

### ISSUE THREAD

**Issue by elliotwutingfeng** [ssddanbrown/Open-Source-Confusers#1]
[NumWorks](https://news.ycombinator.com/item?id=27126926) accepts "open-source" style contributions to their [epsilon](https://github.com/numworks/epsilon) repository via pull requests even though they are under a strong copyright license.

**Comment by ssddanbrown** [comment]
Thanks for the submission @elliotwutingfeng.

Looking into this, it does look like there [has been confusion here](https://github.com/numworks/epsilon/issues/38), and license changes which have [caused confusion](https://github.com/numworks/epsilon/issues/1875). 

That said, I'm not sure they're knowingly, and significantly, propagating confusion in the current state of things.
Apart from a few translations, I can't see active merging of community pull requests since the license change, and it looks like most community activity is now in the [Omega repo](https://github.com/Omega-Numworks/Omega).

That's not to say there's not confusion at play, their readme still welcomes contributions while providing no specific rights to users for any actions. But I don't see evidence that this particular point has been raised with them in their current license state (Only in old previous license sates).

**Comment by elliotwutingfeng** [comment]
Yes, while it probably isn't a good idea to make pull requests to their repository, as of now they aren't claiming to be open-source in any misleading way.
